config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients
  root "home#index"
  get '/about', to: 'home#about'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    # Print out the value of the instance variable @patients, loop throught each of them
    # and print out the value of each patient's name attribute.
    # allow only authenticated users to view the list of patients
    if user_signed_in?
      @patients = Patient.all
    else
      redirect_to new_user_session_path
    end
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    if user_signed_in?
      @patient = Patient.new
    else
      redirect_to new_user_session_path
    end
  end

  # GET /patients/1/edit
  def edit
    if user_signed_in?
      @patient = Patient.find(params[:id])
    else
      redirect_to new_user_session_path
    end
  end

  # POST /patients or /patients.json
  def create
    if user_signed_in?
      @patient = Patient.new(patient_params)

      respond_to do |format|
        if @patient.save
          format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
          format.json { render :show, status: :created, location: @patient }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    if user_signed_in?
      respond_to do |format|
        if @patient.update(patient_params)
          format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
          format.json { render :show, status: :ok, location: @patient }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @patient.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    if user_signed_in?
      @patient.destroy

      respond_to do |format|
        format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      redirect_to new_user_session_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :email, :problem)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/home/about.html.erb
About Me

app/views/home/index.html.erb
<br />  <br /> <br /> <br /> 
  
  <div class="d-flex h-100 text-center">

    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

  <main class="px-3">
    <h1>Patients App</h1>
    <p class="lead">
        A Simple App where Doctors and Receptionists can add patients and their problems and can view them.
        Only Doctors can edit and delete the patients.

    
    </p>
    <p class="lead">
        To get started, please sign up or sign in.    
    </p>
    <p class="lead">


    <% if user_signed_in? %>
    <%= link_to "View Patients", patients_path, class: "btn btn-lg btn-light fw-bold border-white bg-white"  %>
      <% else %>


      <%= link_to "Sign In", new_user_session_path, class: "btn btn-lg btn-light fw-bold border-white bg-white"  %>
      <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-light fw-bold border-white bg-white"  %>
      <% end %>
    </p>
  </main>

 

    

</div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
      <%= yield(:title) || "Ruby on Rails Tutorial Sample App" %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>

  <body class="container-fluid">
    <%= render "layouts/partials/header" %>

    <% if notice %>
      <%= render "layouts/partials/alerts" %>
    <% end %>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/partials/_alerts.html.erb
<br/>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/partials/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Patients App", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link"  %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Patients", patients_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
        <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign out", destroy_user_session_path, class:"nav-link" %>
        </li>
        <% else %>
        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class: "nav-link"  %>
        </li>
        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link"  %>
        </li>



        <% end %>
        
        
      </ul>
    </div>
  </div>
</nav>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :problem, style: "display: block" %>
    <%= form.text_field :problem %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/_patient.html.erb
<div id="<%= dom_id patient %>">
  <p>
    <strong>Name:</strong>
    <%= patient.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= patient.email %>
  </p>

  <p>
    <strong>Problem:</strong>
    <%= patient.problem %>
  </p>

</div>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<div class='row'>
  <div class='col-md-4 text-center mx-auto'>
    <%= form_with model: @patient do |form| %>
      <div class="mb-3">
        <%= form.label :name, class:"form-label" %>
        <%= form.text_field :name, class:"form-control", placeholder:"Your Name ..." %>
      </div>
      <div class="mb-3">
        <%= form.label :email, class:"form-label" %>
        <%= form.text_field :email, class:"form-control", placeholder:"Your Email ..." %>
      </div>
      <div class="mb-3">
        <%= form.label :problem, class:"form-label" %>
        <%= form.text_area :problem, class:"form-control", placeholder:"Your Problem ..." %>
      </div>
      <div>
        <%= form.submit "Update patient", class:"btn btn-success" %>
      </div>
    <% end %>
    <div class="mt-3">
  <%= link_to "Back to patients", patients_path, class:"" %>
</div>
      <div class="mt-3">
      <%= link_to "Show this patient", @patient %>
      </div>
  </div>
</div>

app/views/patients/index.html.erb
<div class="mb-5">
<div class="mx-3 float-start">
<h1>Patients</h1>
</div>

<div class="float-end ">

<%= link_to "New patient", new_patient_path, class:"mx-3 btn btn-secondary" %>
</div>

</div>

<div class="mt-5">
<div id="patients" class="container">
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Problem</th>
      <th scope="col">Created On</th>
    </tr>
  </thead>
  <% @patients.each do |patient| %>
    <tbody>
    <tr>
      <th scope="row">
        <%= link_to patient.name, patient_path(patient) %>
      </th>
      <td>
        <%= patient.email %>
      </td>
      <td>
      <%= patient.problem %>
      </td>
      <td>
        <%= patient.created_at.strftime("%B %d, %Y") %>
      </td>
    </tr>
    </tbody>
  <% end %>
  </table>
</div>

</div>

app/views/patients/new.html.erb
<h1>New patient</h1>

<div class='row'>
  <div class='col-md-4 text-center mx-auto'>
    <%= form_with model: @patient do |form| %>
      <div class="mb-3">
        <%= form.label :name, class:"form-label" %>
        <%= form.text_field :name, class:"form-control", placeholder:"Your Name ..." %>
      </div>
      <div class="mb-3">
        <%= form.label :email, class:"form-label" %>
        <%= form.text_field :email, class:"form-control", placeholder:"Your Email ..." %>
      </div>
      <div class="mb-3">
        <%= form.label :problem, class:"form-label" %>
        <%= form.text_area :problem, class:"form-control", placeholder:"Your Problem ..." %>
      </div>
      <div>
        <%= form.submit "Create patient", class:"btn btn-success" %>
      </div>
    <% end %>
    <div class="mt-3">
  <%= link_to "Back to patients", patients_path, class:"" %>
</div>
  </div>
</div>

app/views/patients/show.html.erb
<div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
        <h3 class="display-5 fw-bold">
        
        <%= @patient.name %> | <%= @patient.email %>
        
        </h3>
        <p class="col-md-8 fs-4">
        <%= @patient.problem %>
        </p>
        <%= link_to "Edit this patient", edit_patient_path(@patient), class:"btn btn-secondary btn-md" %>
        <%= link_to "Back to patients", patients_path, class:"btn btn-secondary btn-md" %>

        <br />
        <%= button_to "Delete this patient", @patient, method: :delete, class:"mt-4 btn btn-danger btn-md" %>

      </div>
    </div>